name: Terraform Infra CI/CD

on:
  push:
    paths:
      - 'infra/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    # Clone the repo into the runner VM
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Configure AWS credentials using GitHub secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        working-directory: infra
        run: terraform init

      - name: Validate Terraform
        working-directory: infra
        run: terraform validate

      - name: Plan Terraform
        working-directory: infra
        run: terraform plan -out=tfplan

      - name: Show Terraform Plan
        working-directory: infra
        run: terraform show -no-color tfplan

      #  Apply Terraform (only on main branch)
      - name: Apply Terraform
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
